name: mediaapp
description: A new approach to audio books for kids

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  connectivity: ^3.0.3
  carousel_slider: ^3.0.0
  flutter_markdown: ^0.6.1
  #The following adds the text-to-speech function to the application
  flutter_tts: ^3.0.0
  #The following adds the vibration function to the app
  vibration: ^1.7.3
  #The following adds a blinking text function for simplyfing the blinking of the cooking timer or timers in general
  blinking_text: ^1.0.1+2
  #The following adds animated flutter widgets, allowing easier manipulation of certain animations for widgets, i.e. a shake-animation
  animated_widgets: ^1.0.6
  #Video Player for the tutorials
  video_player: ^2.1.9

  #AutoSizeText
  auto_size_text: ^2.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  audioplayers: ^0.20.0
  permission_handler: ^6.1.1
  shared_preferences: ^2.0.5
  utf: ^0.9.0
  sqflite: ^2.0.0+3
  provider:
  marquee: ^2.0.0
  path_provider: ^2.0.1
  path:
  uuid: ^3.0.4
  sprintf:
  ext_storage:
  flutter_bloc: ^7.0.0
  splashscreen:
  volume_watcher: ^1.3.1
  get_it: ^6.1.1
  equatable: ^2.0.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  dio: ^4.0.0
  global_configuration: ^2.0.0-nullsafety.1
  formz: ^0.3.2
  dartz: ^0.9.2
  pin_code_fields: ^7.0.0
  sliding_up_panel: ^1.0.2
  google_sign_in: ^5.0.2
  sign_button: ^2.0.0
  cached_network_image: ^3.0.0
  file_picker: ^3.0.2+2
  audio_session: ^0.1.2
  another_flushbar: ^1.10.23
  bubble_tab_indicator: ^0.1.6
  fl_chart: ^0.36.3
  flutter_image_map: ^0.9.2
  badges: ^2.0.1
  confetti: ^0.5.5
  flutter_animation_progress_bar: ^2.0.0
  sizer: ^2.0.13
  rive: ^0.7.22
  animated_text_kit: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  android: true
  ios: true
  image_path: "graphics/parrotA.png"

  # For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - graphics/
    - graphics/profile/
    - graphics/profiles_pictures/ # TODO: Remove entry + remove directory and files
    - graphics/audiobook/
    # FlockeIcon made by Pixel perfect from www.flaticon.com
    # BackgroundImage. This cover has been designed using resources from Freepik.com
    - graphics/hidden_letter/
    - graphics/webpage/
    - graphics/fourwinsgraphics/
    - graphics/tictactoegraphics/
    - graphics/memorycards/
    - graphics/icons/
    - graphics/anlauttabelle/
    - graphics/buchstabentabelle/
    - graphics/word_pictures/
    - graphics/syllable_house/
    - graphics/syllable_matching/
    - graphics/test_Anlauttabelle/
    - graphics/anlauttabelle/
    - graphics/buchstabentabelle/
    - graphics/word_pictures/
    - graphics/assignletters/
    - locale/i18n_en.json
    - locale/i18n_de.json
    - sample_data/
    - sample_data/coloring_book/
    - sample_data/handcraft/
    - sample_data/handcraft/instructions/
    - sample_data/cooking_recipe/
    - sample_data/cooking_recipe/recipes/
    - sample_data/word_picture_assignment/
    - sample_data/syllable_memory/
    - sample_data/letter_assignment/
    - sample_data/letter_assignment/levels/
    - assets/cfg/
    - assets/sounds/CookingAlarm.mp3
    - assets/sample/
    - assets/videos/
    - assets/videos/syllable_house/
    - assets/videos/word_picture_assignment/
    - sample_data/syllable_house/
    - sample_data/syllable_house/themes/
    - sample_data/syllable_matching/
    - sample_data/syllable_games/
    - assets/sounds/
    - sample_data/hidden_letters/
    - assets/sounds/syllable_matching/
    - assets/videos/
    - assets/videos/syllable_matching/
    - assets/sounds/letter_assignment/
    - assets/sounds/word_picture_assignment/

  fonts:
    - family: GrundSchriftPunkt
      fonts:
        - asset: fonts/grundschrift_punkt.otf
    - family: NilamTracingABC
      fonts:
        - asset: fonts/nilam_tracing_abc.ttf
    - family: Alfabilder
      fonts:
        - asset: fonts/Alfabilder.ttf
    - family: CustomIconEraser
      fonts:
        - asset: fonts/custom_icon_eraser.ttf
    - family: ABeeZee
      fonts:
        - asset: fonts/abeezee_regular.ttf
    - family: Comforaa
      fonts:
        - asset: fonts/comfortaa_light.ttf
    - family: Cormorant
      fonts:
        - asset: fonts/cormorant_infant.otf
    - family: Exo
      fonts:
        - asset: fonts/exo_2.0_extra_light_italic.otf
    - family: Rancho
      fonts:
        - asset: fonts/rancho_regular.ttf
    - family: Sans
      fonts:
        - asset: fonts/source_sans_pro_italic.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
